workflow:
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: $CI_COMMIT_BRANCH && $CI_OPEN_MERGE_REQUESTS
      when: never
    - if: $CI_PIPELINE_SOURCE == "push"
      when: never
    - if: $CI_COMMIT_BRANCH
      when: always

include:
  - project: 'searchanise/git-workflow'
    ref: 'main'
    file: 'setup-code-and-requirements.yml'

variables:
  SE_MIGRATE_ENABLE: "false"
  GIT_CLEAN_FLAGS: -ffd
  SE_PROJECT_NAME: idoc
  SE_PSALM_ENABLED: "false"
  SE_RUN_NPM_CI: "false"
  SE_IS_LARAVEL: "false"
  SE_PINT_ENABLED: "false"

services:
  - name: docker:24-dind

stages:
  - tests

Unit_Tests:
  stage: tests
  script:
    - php ./vendor/bin/php-cs-fixer check -v --format=gitlab
    - composer test
  tags:
    - docker
